using System.ComponentModel.DataAnnotations;

namespace DotNet2023.DataModel.Organization;

/// <summary>
/// The class describes the basic type of organization (places of work)
/// <param name="Id">Autogenerated primary key in string format. Represents Guid</param>
/// <param name="FullName">Full name of the organization (as in the documents)</param>
/// <param name="Initials">The initials of the organization</param>
/// <param name="LegalAddress">Legal address of the organization (as in the documents)</param>
/// <param name="RegistrationNumber">Registration number of the organization</param>
/// <param name="Email">Email. Format lalala@lala.la</param>
/// <param name="Phone"> Phone.Format @[0-9]{11}</param>
/// </summary>
public class Organization
{
    [Required]
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();

    public string? FullName { get; set; }
    public string? Initials { get; set; }

    // TODO: create a regular expression type of "lalala. Country. Region. City. Address"
    public string? LegalAddress { get; set; }


    [RegularExpression(@"[0-9]{13}")]
    public string? RegistrationNumber { get; set; }

    [RegularExpression(@"[0-9]{10}")]
    public string? Phone { get; set; }

    [RegularExpression(@"\\S+@\\S+\\.\\S+$")]
    public string? Email { get; set; }
}
